version: "3.1"
# networks:
#   app-tier:
#     driver: bridge
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
      # - MONGO_INITDB_ROOT_DATABASE=bar
      # - MONGO_USERDB_AUTH_USERNAME=root2
      # - MONGO_USERDB_AUTH_PASSWORD=1234
      # - MONGO_USERDB_AUTH_DATABASE=bar
      - MONGO_INITDB_DATABASE=bar
    ports:
      - 27018:27017
    volumes:
      - "./data/db:/data/db"
      # - "./mongod.conf:/etc/mongod.conf"
      - "./mongo1-init.js:/docker-entrypoint-initdb.d/mongo1-init.js:ro"

  mongo_express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=bar
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  # adminerphp:
  #   image: dockette/adminer:full-php5
  #   restart: always
  #   ports:
  #     - 8080:80
  #     # - 8080:8080
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mongodb
  #   depends_on:
  #     - mongodb

  crawler:
    build: .
    volumes:
      - .:/scrapy
    depends_on:
      - mongodb
